apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Jenkins-test-template
  title: Jenkins test template
  description: Test template
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - prod

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=jk7testorg&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
        
    - id: trigger-jenkins-scan
      name: Trigger Jenkins Organization Scan
      action: executeShellCommand
      input:
        command: |
          #!/bin/bash
          set -e
          JENKINS_HOST="https://donella-bionomic-thermostatically.ngrok-free.dev"
          ORG_FOLDER="jk7testjenkins"
          USER="backstage"
          TOKEN="1193767a732b9753cd50379fed792de2d4"
          
          CRUMB=$(curl -s -u "${USER}:${TOKEN}" \
            "https://${JENKINS_HOST}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          curl -X POST "https://${JENKINS_HOST}/job/${ORG_FOLDER}/build" \
            -u "${USER}:${TOKEN}" \
            -H "${CRUMB}"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}









