apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.component_id}}
  namespace: argocd
  labels:
    backstage.io/component: ${{values.component_id}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${{values.repoUrl}}
    targetRevision: main
    path: ${{values.component_id}}/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
