apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.component_id}}
    backstage.io/component: ${{values.component_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
    spec:
      containers:
        - name: ${{values.component_id}}
          image: ${{values.image}}:${{values.tag}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
