apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.component_id}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.component_id}}
    backstage.io/component: ${{values.component_id}}
  annotations:
    kubernetes.io/ingress.class: "nginx"                          # shared ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /${{values.component_id}}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${{values.component_id}}
                port:
                  number: 80
